# This workflow is triggered when code changes are pushed to main.
# The first step uses scan-git to clone and delta scan main.
# The second uses evaluate-gates to fail if Pending IDs or Policy Violations exist.

name: Test Scan-Git and Evaluate Gates
on: 
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  workbench-scan-gate:
    runs-on: ubuntu-latest
    env:
      WORKBENCH_URL: ${{ secrets.WORKBENCH_URL }}
      WORKBENCH_USER: ${{ secrets.WORKBENCH_USER }}
      WORKBENCH_TOKEN: ${{ secrets.WORKBENCH_TOKEN }}
    steps:
    - name: Clone from Git and Scan
      run: |
        docker run ghcr.io/fossid-ab/workbench-agent:latest \
        scan-git \
        --api-url ${{ env.WORKBENCH_URL }} \
        --api-user ${{ env.WORKBENCH_USER }} \
        --api-token ${{ env.WORKBENCH_TOKEN }} \
        --project-name DogFood-$GITHUB_REPOSITORY \
        --scan-name ScanGit-$GITHUB_REF_NAME \
        --git-url $GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
        --git-branch $GITHUB_REF_NAME \
        --git-depth 1 \
        --reuse-project-ids $GITHUB_REPOSITORY \
        --run-dependency-analysis \
        --autoid-file-licenses \
        --autoid-file-copyrights \
        --delta-scan \
        --no-wait

    - name: Evaluate Gates; Fail on Issues
      run: |
        docker run ghcr.io/fossid-ab/workbench-agent:latest \
        evaluate-gates \
        --api-url ${{ env.WORKBENCH_URL }} \
        --api-user ${{ env.WORKBENCH_USER }} \
        --api-token ${{ env.WORKBENCH_TOKEN }} \
        --project-name DogFood-$GITHUB_REPOSITORY \
        --scan-name ScanGit-$GITHUB_REF_NAME \
        --fail-on-pending \
        --fail-on-policy
